name: slately
description: We won't judge your old wallpaper. But we will replace it.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  device_info_plus: ^9.0.3
  fluttertoast: ^8.2.2
  flutter_screenutil: ^5.8.4
  flutter_easyloading: ^3.0.5
  flutter_svg: ^1.1.6
  logger: ^2.0.1
  connectivity_plus: ^4.0.2
  cached_network_image: ^3.2.3
  get: ^4.6.6
  get_storage: ^2.1.1
  http: any
  dio: any
#  flutter_native_splash: ^2.3.2
#  flutter_launcher_icons: any
  flutter_animate: ^4.2.0+1
  cloudinary: ^1.2.0
  image_picker: ^1.0.7
  permission_handler: ^11.3.0
  flutter_dotenv: ^5.1.0
  async_wallpaper: ^2.0.3



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/
    - assets/icons/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700


#flutter_launcher_icons:
#  ios: true
#  android: true
#  image_path: "assets/images/app_icon.png"
#  remove_alpha_ios: true
#  adaptive_icon_background: "#272727"
#  adaptive_icon_foreground: "assets/images/app_icon.png"
#  min_sdk_android: 21 # android min sdk min:16, default 21


flutter_native_splash:
  color: "#000000"
  #background_image: "assets/background.png"
  image: assets/images/app_icon.png
  android: true
  ios: false
  color_dark: "#000000"
  #background_image_dark: "assets/dark-background.png"
  image_dark: assets/images/app_icon.png
  #branding_dark: assets/dart_dark.png
  # Android 12 handles the splash screen differently than previous versions.  Please visit
  # https://developer.android.com/guide/topics/ui/splash-screen
  # Following are Android 12 specific parameter.
  android_12:
    image: assets/images/app_icon.png

    # Splash screen background color.
    color: "#000000"

    # App icon background color.
    #icon_background_color: "#111111"

    # The branding property allows you to specify an image used as branding in the splash screen.
    #branding: assets/dart.png

    # The image_dark, color_dark, icon_background_color_dark, and branding_dark set values that
    # apply when the device is in dark mode. If they are not specified, the app will use the
    # parameters from above.
    image_dark: assets/images/app_icon.png
    color_dark: "#000000"
    #icon_background_color_dark: "#eeeeee"
  fullscreen: true
